POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"henry12",
    "password":"henry"
}


###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"henry12",
    "password":"henry"
}

###

POST http://localhost:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTZhNjE3M2UxOGQwODlhNjM2NmVhY2YiLCJpYXQiOjE2MzQzNzM4NzB9.CNk6zRNTix4CaMldAaF04_0jdxtENOwNe-_pG0xQGq8

{
    "title":"my first post",
    "description":"abc",
    "url":"google.com",
    "status":"LEARNING"

}

### 
GET http://localhost:5000/api/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTZhNjE3M2UxOGQwODlhNjM2NmVhY2YiLCJpYXQiOjE2MzQzNzM4NzB9.CNk6zRNTix4CaMldAaF04_0jdxtENOwNe-_pG0xQGq8
###
PUT http://localhost:5000/api/posts/616a9155868e5cbd0664fab8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTZhNjE3M2UxOGQwODlhNjM2NmVhY2YiLCJpYXQiOjE2MzQzNzM4NzB9.CNk6zRNTix4CaMldAaF04_0jdxtENOwNe-_pG0xQGq8

{
    "title":"my first post2",
    "description":"abc2",
    "url":"google.com",
    "status":"LEARNING"

}

###
DELETE http://localhost:5000/api/posts/616a9155868e5cbd0664fab8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTZhNjE3M2UxOGQwODlhNjM2NmVhY2YiLCJpYXQiOjE2MzQzNzM4NzB9.CNk6zRNTix4CaMldAaF04_0jdxtENOwNe-_pG0xQGq8
